### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by darkzbaron** [vahe-evoyan/pocketcasts-desktop#1]

**Comment by darkzbaron** [comment]
HI there, im trying to run the script with npm start to no avail. I have no experience with js scrips. Would you be able to help?

**Comment by vahe-evoyan** [comment]
Hi @darkzbaron, unfortunately it is not finished yet. Will let you know when it's ready. When it's done you won't need any experience with JS, it'll provide platform specific packages.

**Comment by darkzbaron** [comment]
ok cool. Thanks so much for the quick reply

**Comment by darkzbaron** [comment]
Hello how are you? I just came across this one. https://github.com/MaienM/PocketcastsUtils  .  do you have any experience with it? Thanks,Jonathan

**Comment by vahe-evoyan** [comment]
Hey @darkzbaron, in case you're still interested, I just released a preliminary version for MacOS only.

https://github.com/vahe-evoyan/pocketcasts-desktop/releases

**Comment by darkzbaron** [comment]
Hi Vahe, thanks for thanks for heads up and massive congratulations on your release. I am on windows unfortunately. Also someone built an official api in Python, I am usin this for the momen but I would still be interested in a proper desktop app

**Comment by darkzbaron** [comment]
https://github.com/exofudge/Pocket-Casts
